### ISSUE TITLE
Make it  easier to getting started

### ISSUE THREAD

**Issue by zoosewu** [va4ok/userscript-builder#28]
I'm following your "Getting Started", I don't know what should do after ```npm install --save-dev userscript-builder```, no matter I tried command ```npm run userscript-builder``` it doens't work and send me error:
```
npm ERR! missing script: userscript-builder

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\username\AppData\Local\npm-cache\_logs\2020-12-16T15_42_48_538Z-debug.log
```
And here is the following log:
```
0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'run',
0 verbose cli   'userscript-builder'
0 verbose cli ]
1 info using npm@7.0.15
2 info using node@v15.4.0
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 2ms
5 timing config:load:builtin Completed in 2ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:E:\Project\myproject\.npmrc Completed in 1ms
9 timing config:load:project Completed in 3ms
10 timing config:load:file:C:\Users\username\.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:C:\Users\username\AppData\Roaming\npm\etc\npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 10ms
19 verbose npm-session 99230f49e06e6296
20 timing npm:load Completed in 19ms
21 timing command:run-script Completed in 1ms
22 verbose stack Error: missing script: userscript-builder
22 verbose stack     at runScript (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:54:11)
23 verbose cwd E:\Project\myproject
24 verbose Windows_NT 10.0.17763
25 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "userscript-builder"
26 verbose node v15.4.0
27 verbose npm  v7.0.15
28 error missing script: userscript-builder
29 verbose exit 1
```
Finally I found ```"example:dev": "node ./bin/builder.js --mode dev"``` in package.json file in the ```node_modules\userscript-builder```, and I succed with command in the module file like ```E:\Project\myproject\node_modules\userscript-builder>node ./bin/builder.js --mode dev``` finally.

However I still don't know what should I do next, I should copy bin and builder to myproject folder? or should i put command like```E:\Project\myproject>node .node_modules/userscript-builder/bin/builder.js --mode dev```?
Is there any way to instance file automatically and let me run command sussesful at myproject?

I'm new at nodejs thanks.

My system info:
Windows_NT 10.0.17763
npm@7.0.15
node@v15.4.0

Here is my project dir: E:\Project\myproject
Here is the way I found command can run: E:\Project\myproject\node_modules\userscript-builder\package.json

**Comment by va4ok** [comment]
Hi @zoosewu sorry for delay
Yeah some error in doc.
You need to add update your scripts section of package.json with something like 
```
"scripts": {
    "build": "userscript-builder --mode dev",
    "release:bugfix": "userscript-builder --mode bugfix",
    "release:minor": "userscript-builder --mode minor",
    "release:major": "userscript-builder --mode major"
  },
```
and then you can use command like `npm run release:bugfix`
as a sort of production example you can see into https://github.com/va4ok/jira2git-tools/blob/master/package.json

**Comment by zoosewu** [comment]
Thanks, this info is what I need, and it work well now.
Is it possible to add these scripts to ```package.json``` automatically when user install this module?

**Comment by va4ok** [comment]
I can make an assumption that end user can already have tasks with the same names, so it can be a disservice.
I have plan to update interface with semantic version e.g. patch, minor, major `userscript-builder patch`
And one more thing - because of new Chrome api i believe we can lose TamperMonkey as a class of chrome extensions.
