### ISSUE TITLE
Minifying release output code

### ISSUE THREAD

**Issue by rzlnhd** [va4ok/userscript-builder#32]
Hi... I recently try this module, it works really good,... I'm new on node.js by the way... So, may I ask you something?
On my project, I need to minify the code on the release output... Which node module can I try for this, and how do I modify the `script` on package.json?

Thanks...

**Comment by va4ok** [comment]
Hi, you can use some minify tools like uglify, webpack. I believe it is no need to add minification into userscript-builder because this is a very specific and lightweight tool for tampermankey.
